//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Museum
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Contact.
    /// </summary>
    //  *** Start programmer edit section *** (Contact CustomAttributes)

    //  *** End programmer edit section *** (Contact CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ContactE", new string[] {
            "Name as \'Name\'",
            "Tel as \'Tel\'",
            "Active as \'Active\'"})]
    [View("ContactL", new string[] {
            "Name as \'Name\'",
            "Tel as \'Tel\'",
            "Active as \'Active\'"})]
    public class Contact : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fTel;
        
        private bool fActive = true;
        
        //  *** Start programmer edit section *** (Contact CustomMembers)

        //  *** End programmer edit section *** (Contact CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Contact.Name CustomAttributes)

        //  *** End programmer edit section *** (Contact.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Contact.Name Get start)

                //  *** End programmer edit section *** (Contact.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Contact.Name Get end)

                //  *** End programmer edit section *** (Contact.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Contact.Name Set start)

                //  *** End programmer edit section *** (Contact.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Contact.Name Set end)

                //  *** End programmer edit section *** (Contact.Name Set end)
            }
        }
        
        /// <summary>
        /// Tel.
        /// </summary>
        //  *** Start programmer edit section *** (Contact.Tel CustomAttributes)

        //  *** End programmer edit section *** (Contact.Tel CustomAttributes)
        [StrLen(255)]
        public virtual string Tel
        {
            get
            {
                //  *** Start programmer edit section *** (Contact.Tel Get start)

                //  *** End programmer edit section *** (Contact.Tel Get start)
                string result = this.fTel;
                //  *** Start programmer edit section *** (Contact.Tel Get end)

                //  *** End programmer edit section *** (Contact.Tel Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Contact.Tel Set start)

                //  *** End programmer edit section *** (Contact.Tel Set start)
                this.fTel = value;
                //  *** Start programmer edit section *** (Contact.Tel Set end)

                //  *** End programmer edit section *** (Contact.Tel Set end)
            }
        }
        
        /// <summary>
        /// Active.
        /// </summary>
        //  *** Start programmer edit section *** (Contact.Active CustomAttributes)

        //  *** End programmer edit section *** (Contact.Active CustomAttributes)
        public virtual bool Active
        {
            get
            {
                //  *** Start programmer edit section *** (Contact.Active Get start)

                //  *** End programmer edit section *** (Contact.Active Get start)
                bool result = this.fActive;
                //  *** Start programmer edit section *** (Contact.Active Get end)

                //  *** End programmer edit section *** (Contact.Active Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Contact.Active Set start)

                //  *** End programmer edit section *** (Contact.Active Set start)
                this.fActive = value;
                //  *** Start programmer edit section *** (Contact.Active Set end)

                //  *** End programmer edit section *** (Contact.Active Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ContactE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactE", typeof(IIS.Museum.Contact));
                }
            }
            
            /// <summary>
            /// "ContactL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactL", typeof(IIS.Museum.Contact));
                }
            }
        }
    }
}
