//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Museum
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Melon.
    /// </summary>
    //  *** Start programmer edit section *** (Melon CustomAttributes)

    //  *** End programmer edit section *** (Melon CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MelonE", new string[] {
            "Color as \'Color\'",
            "Weight as \'Weight\'"})]
    [View("MelonL", new string[] {
            "Color as \'Color\'",
            "Weight as \'Weight\'"})]
    public class Melon : ICSSoft.STORMNET.DataObject
    {
        
        private string fColor;
        
        private double fWeight;
        
        //  *** Start programmer edit section *** (Melon CustomMembers)

        //  *** End programmer edit section *** (Melon CustomMembers)

        
        /// <summary>
        /// Color.
        /// </summary>
        //  *** Start programmer edit section *** (Melon.Color CustomAttributes)

        //  *** End programmer edit section *** (Melon.Color CustomAttributes)
        [StrLen(255)]
        public virtual string Color
        {
            get
            {
                //  *** Start programmer edit section *** (Melon.Color Get start)

                //  *** End programmer edit section *** (Melon.Color Get start)
                string result = this.fColor;
                //  *** Start programmer edit section *** (Melon.Color Get end)

                //  *** End programmer edit section *** (Melon.Color Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Melon.Color Set start)

                //  *** End programmer edit section *** (Melon.Color Set start)
                this.fColor = value;
                //  *** Start programmer edit section *** (Melon.Color Set end)

                //  *** End programmer edit section *** (Melon.Color Set end)
            }
        }
        
        /// <summary>
        /// Weight.
        /// </summary>
        //  *** Start programmer edit section *** (Melon.Weight CustomAttributes)

        //  *** End programmer edit section *** (Melon.Weight CustomAttributes)
        public virtual double Weight
        {
            get
            {
                //  *** Start programmer edit section *** (Melon.Weight Get start)

                //  *** End programmer edit section *** (Melon.Weight Get start)
                double result = this.fWeight;
                //  *** Start programmer edit section *** (Melon.Weight Get end)

                //  *** End programmer edit section *** (Melon.Weight Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Melon.Weight Set start)

                //  *** End programmer edit section *** (Melon.Weight Set start)
                this.fWeight = value;
                //  *** Start programmer edit section *** (Melon.Weight Set end)

                //  *** End programmer edit section *** (Melon.Weight Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MelonE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MelonE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MelonE", typeof(IIS.Museum.Melon));
                }
            }
            
            /// <summary>
            /// "MelonL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MelonL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MelonL", typeof(IIS.Museum.Melon));
                }
            }
        }
    }
}
